services:
  # Servicio Web
  - type: web
    name: el-rincon-del-mentiroso
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

  # Variables de entorno específicas para Render
    autoDeploy: true
