services:
  # Servicio Web
  - type: web
    name: el-rincon-del-mentiroso
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://admin_cruel:28dejulio@cluster0.lvswgvg.mongodb.net/admin?appName=Cluster0
      - key: JWT_SECRET
        value: el-rincon-del-mentiroso-super-secreto-2024
      - key: UPLOADS_DIR
        value: /tmp/uploads
      - key: FILE_RETENTION_DAYS
        value: 3
    autoDeploy: true
